# Generated by Django 2.2.2 on 2019-06-27 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=32, unique=True, verbose_name='车辆识别代码')),
                ('plate', models.CharField(max_length=16, unique=True, verbose_name='车牌号')),
                ('vtype', models.CharField(blank=True, max_length=16, verbose_name='车辆类型')),
                ('owner', models.CharField(blank=True, max_length=16, verbose_name='所有人')),
                ('character', models.IntegerField(choices=[(1, '非营运'), (2, '营运')], default=1, verbose_name='使用性质')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bound_user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boundVehicles', to=settings.AUTH_USER_MODEL, verbose_name='绑定车主')),
            ],
            options={
                'verbose_name': '机动车',
                'verbose_name_plural': '机动车',
                'db_table': 'vehicle',
            },
        ),
    ]
