# Generated by Django 2.2.2 on 2019-06-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('SUPERADMIN', '超级管理员'), ('STATIONADMIN', '检查点管理员'), ('CLIENT', '普通用户')], default='client', max_length=16, verbose_name='用户类型'),
        ),
    ]
