# Generated by Django 2.2.2 on 2019-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190627_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('SUPERADMIN', '超级管理员'), ('STATIONADMIN', '检查点管理员'), ('CLIENT', '普通用户')], default='CLIENT', max_length=16, verbose_name='用户类型'),
        ),
    ]
