# Generated by Django 2.2.2 on 2019-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190628_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/avatar/head.gif', upload_to='avatar', verbose_name='头像'),
        ),
    ]
