# Generated by Django 2.2.2 on 2019-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190703_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', '超级管理员'), ('STATIONADMIN', '检查点管理员'), ('CLIENT', '普通用户')], default='CLIENT', max_length=16, verbose_name='用户角色'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/media/avatar/head.gif', upload_to='avatar', verbose_name='头像'),
        ),
    ]
