# Generated by Django 2.2.2 on 2019-07-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190704_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='id_card',
        ),
    ]
