# Generated by Django 2.2.2 on 2019-06-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='检测站名称')),
                ('contact', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='地址')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '车辆检测站',
                'verbose_name_plural': '车辆检测站',
                'db_table': 'InspStation',
            },
        ),
        migrations.CreateModel(
            name='AppointmentRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('am_start_time', models.TimeField(default='08:00', verbose_name='上午检测开始时间')),
                ('am_end_time', models.TimeField(default='11:00', verbose_name='上午检测结束时间')),
                ('pm_start_time', models.TimeField(default='13:00', verbose_name='下午检测开始时间')),
                ('pm_end_time', models.TimeField(default='17:00', verbose_name='下午检测结束时间')),
                ('cutoff_time', models.TimeField(default='16:00', verbose_name='当天截止预约时间')),
                ('interval', models.IntegerField(default=60, verbose_name='时间间隔(分钟)')),
                ('threshold', models.IntegerField(default=20, verbose_name='单个时间段最大预约数')),
                ('station', models.OneToOneField(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointmentRule', to='station.InspStation', verbose_name='车辆检测站')),
            ],
            options={
                'verbose_name': '预约规则',
                'verbose_name_plural': '预约规则',
                'db_table': 'AppointmentRule',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(unique=True, verbose_name='日期')),
                ('can_order', models.BooleanField(default=True, verbose_name='能否预约')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointmentDays', to='station.InspStation', verbose_name='车辆检测站')),
            ],
            options={
                'verbose_name': '预约时间',
                'verbose_name_plural': '预约时间',
                'db_table': 'AppointmentDay',
            },
        ),
    ]
