# Generated by Django 2.2.2 on 2019-06-26 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_inspstation_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrule',
            name='interval',
            field=models.IntegerField(choices=[(60, '1小时'), (90, '1个半小时'), (120, '2小时')], default=60, verbose_name='时间间隔'),
        ),
        migrations.AlterField(
            model_name='inspstation',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
