# Generated by Django 2.2.2 on 2019-07-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20190626_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentday',
            name='day',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentday',
            unique_together={('station', 'day')},
        ),
    ]
