# Generated by Django 2.2.2 on 2019-07-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20190703_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentday',
            name='weekday',
            field=models.CharField(blank=True, max_length=16, verbose_name='星期'),
        ),
    ]
