# Generated by Django 2.2.2 on 2019-06-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentorder',
            name='scheduled_date',
            field=models.DateField(db_index=True, verbose_name='预约日期'),
        ),
    ]
