# Generated by Django 2.2.2 on 2019-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appmntorderagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentorder',
            name='plate',
            field=models.CharField(default='', max_length=16, verbose_name='待检机动车车牌号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentorder',
            name='vin',
            field=models.CharField(default='', max_length=32, verbose_name='待检机动车识别代码'),
            preserve_default=False,
        ),
    ]
